name: Create Release
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to every tag not containing /
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Release Body
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npx standard-version --release-as ${{github.ref_name}} -i RELEASE_BODY.md --skip.bump --skip.commit --skip.tag
      #- name: Publish Tag
      #  id: publish_tag
      #  run: |
      #    git push --follow-tags
      #    echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          body_path: RELEASE_BODY.md
  Deploy-Production:
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
